spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: mango
    password: mango
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default




